name: Build Linux Container Image and Push to ACR

on:
<<<<<<< HEAD
  push:
    branches:
      - main
=======
  workflow_dispatch:
>>>>>>> 8398f9a7dd9967b5c98f1ba59655567f999012cc

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: maintenanceml.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t maintenanceml.azurecr.io/maintenanceml:latest .
        docker push maintenanceml.azurecr.io/maintenanceml:latest
