name: Docker Build and Push Workflow

on:
  workflow_run:
    workflows: ["Test APP Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        login-server: maintenanceml.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t maintenanceml.azurecr.io/maintenanceml:latest .
        docker push maintenanceml.azurecr.io/maintenanceml:latest