name: Test ML Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ejecutar model_test.py
        run: python model_test.py

      - name: Leer el valor de accuracy
        id: read_accuracy
        run: echo "::set-output name=accuracy::$(cat accuracy.txt)"

      - name: Validar precisión
        run: |
          accuracy=$1
          if [ $(echo "$accuracy >= 0.9" | bc -l) -eq 0 ]; then
            echo "Error: La precisión es menor que 0.9"
            exit 1
          fi
        env:
          ACCURACY: ${{ steps.read_accuracy.outputs.accuracy }}

trigger_second_workflow:
  runs-on: ubuntu-latest
  steps:
    - name: Test APP Workflow
      run: echo "Test APP Workflow"

