name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytho test.py 

  trigger_second_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger second workflow
        run: echo "Triggering the second workflow"
