name: Test ML Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        id: test
        run: python model_test.py

      - name: Check accuracy
        if: steps.test.outcome == 'success'
        run: |
          accuracy=$(python -c "print($(cat accuracy.txt) > 0.9)")
          echo "Accuracy is greater than 0.9: $accuracy"
          echo "::set-output name=accuracy::$accuracy"

  trigger_second_workflow:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ needs.test.outputs.accuracy == 'true' }}
    steps:
      - name: Test APP Workflow
        run: echo "Test APP Workflow"
